#!/usr/bin/env bash

# MacSetup Homebrew Maintenance Script
# Provides common maintenance tasks for Homebrew

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Homebrew is installed
check_homebrew() {
    if ! command -v brew &> /dev/null; then
        log_error "Homebrew is not installed. Please run brew.sh first."
        exit 1
    fi
}

# Update Homebrew and all packages
update_all() {
    log_info "Updating Homebrew and all installed packages..."
    
    if brew update; then
        log_success "Homebrew updated successfully"
    else
        log_error "Failed to update Homebrew"
        return 1
    fi
    
    if brew upgrade; then
        log_success "All packages upgraded successfully"
    else
        log_warning "Some packages may have failed to upgrade"
    fi
    
    if brew upgrade --cask; then
        log_success "All cask applications upgraded successfully"
    else
        log_warning "Some cask applications may have failed to upgrade"
    fi
}

# Cleanup Homebrew
cleanup_homebrew() {
    log_info "Cleaning up Homebrew..."
    
    # Remove old versions of installed packages
    if brew cleanup; then
        log_success "Homebrew cleanup completed"
    else
        log_warning "Homebrew cleanup had issues"
    fi
    
    # Remove broken symlinks
    if brew cleanup -s; then
        log_success "Broken symlinks removed"
    else
        log_warning "Failed to remove some broken symlinks"
    fi
}

# Check for issues
doctor_check() {
    log_info "Running Homebrew doctor to check for issues..."
    
    if brew doctor; then
        log_success "No issues found by Homebrew doctor"
    else
        log_warning "Homebrew doctor found some issues (see output above)"
    fi
}

# List outdated packages
list_outdated() {
    log_info "Checking for outdated packages..."
    
    local outdated_formulas
    local outdated_casks
    
    outdated_formulas=$(brew outdated)
    outdated_casks=$(brew outdated --cask)
    
    if [[ -n "$outdated_formulas" ]]; then
        log_warning "Outdated formulas:"
        echo "$outdated_formulas"
    else
        log_success "All formulas are up to date"
    fi
    
    if [[ -n "$outdated_casks" ]]; then
        log_warning "Outdated casks:"
        echo "$outdated_casks"
    else
        log_success "All casks are up to date"
    fi
}

# Backup installed packages
backup_packages() {
    local backup_file="homebrew-backup-$(date +%Y%m%d-%H%M%S).txt"
    
    log_info "Creating backup of installed packages to $backup_file..."
    
    {
        echo "# Homebrew Package Backup - $(date)"
        echo "# Generated by brew-maintenance.sh"
        echo ""
        echo "## Taps"
        brew tap
        echo ""
        echo "## Formulas"
        brew leaves
        echo ""
        echo "## Casks"
        brew list --cask
        echo ""
        echo "## MAS Applications"
        if command -v mas &> /dev/null; then
            mas list
        else
            echo "mas not installed"
        fi
    } > "$backup_file"
    
    log_success "Backup created: $backup_file"
}

# Show usage information
show_usage() {
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  update      Update Homebrew and all packages"
    echo "  cleanup     Clean up Homebrew (remove old versions, broken symlinks)"
    echo "  doctor      Run Homebrew doctor to check for issues"
    echo "  outdated    List outdated packages"
    echo "  backup      Create a backup list of installed packages"
    echo "  full        Run update, cleanup, and doctor (recommended)"
    echo "  help        Show this help message"
    echo ""
    echo "If no command is specified, 'full' will be executed."
}

# Full maintenance routine
full_maintenance() {
    log_info "Running full Homebrew maintenance..."
    update_all
    cleanup_homebrew
    doctor_check
    log_success "Full maintenance completed!"
}

# Main execution
main() {
    check_homebrew
    
    case "${1:-full}" in
        "update")
            update_all
            ;;
        "cleanup")
            cleanup_homebrew
            ;;
        "doctor")
            doctor_check
            ;;
        "outdated")
            list_outdated
            ;;
        "backup")
            backup_packages
            ;;
        "full")
            full_maintenance
            ;;
        "help"|"-h"|"--help")
            show_usage
            ;;
        *)
            log_error "Unknown command: $1"
            show_usage
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
